# Generated by Django 4.1.6 on 2023-02-21 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='password',
            field=models.CharField(default='dsda', max_length=50),
        ),
        migrations.AddField(
            model_name='contractor',
            name='user_name',
            field=models.CharField(default='dsda', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(default='dsda', max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='user_name',
            field=models.CharField(default='dsda', max_length=20),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(max_length=10),
        ),
    ]
