# Generated by Django 4.1.2 on 2023-02-23 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0005_alter_category_id_alter_service_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.CharField(default='', max_length=250),
        ),
    ]
