# Generated by Django 4.1.2 on 2023-02-23 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0008_alter_service_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='images',
            field=models.ImageField(null=True, upload_to='servicios'),
        ),
    ]
