# Generated by Django 4.1.2 on 2023-02-23 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0009_alter_service_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='images',
        ),
    ]
