# Generated by Django 4.1.6 on 2023-02-23 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0010_remove_service_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
