# Generated by Django 4.1.6 on 2023-03-01 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0011_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='images',
            field=models.ImageField(null=True, upload_to='servicios'),
        ),
    ]
