# Generated by Django 4.1.6 on 2023-03-01 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0012_service_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='images',
        ),
    ]
