# Generated by Django 4.1.2 on 2023-03-10 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0016_alter_user_address_alter_user_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_active',
            new_name='usuario_activo',
        ),
        migrations.AddField(
            model_name='user',
            name='usuario_administrador',
            field=models.BooleanField(default=False),
        ),
    ]
