# Generated by Django 4.1.6 on 2023-03-14 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0017_rename_is_active_user_usuario_activo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='category_id',
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
