# Generated by Django 4.1.2 on 2023-04-26 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0019_alter_service_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('comments', models.CharField(default='', max_length=100)),
                ('calification', models.CharField(default='', max_length=250)),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Services.service')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
