# Generated by Django 4.1.2 on 2023-04-26 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0020_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='calification',
            field=models.FloatField(),
        ),
    ]
